### ISSUE TITLE
Home Page - surfacing the Network

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network#157] opened 2017-03-14 21:32 UTC
This issue has been previously discussed in #141. Adding it here since it was part of our QA session. 
- Old offerings at top to be removed 
- Old Projects to be removed
- Add Get involved box 
- Add stay connected box  

Mockup here: https://invis.io/ZJ9YTAGEA#/216715355_Home-Page-Opt1

**Comment by gvn** [comment] 2017-03-14 21:38
Isn't this a dupe of #141?

**Comment by hannahkane** [comment] 2017-03-14 21:41
Yeah, sorry, I think I wasn't being clear earlier, @taisdesouzalessa. This issue I think is well-covered in #141. I think we should keep one or the other, but not both.

**Comment by taisdesouzalessa** [comment] 2017-03-14 21:43
@hannahkane I can close this one, sorry for that. #141 is more complete. One question: #141 is P1 and this is P0, not sure which priority we want to use.

**Closed** 2017-03-14 21:43 UTC
Labels: engineering, p0, quality test

**Comment by hannahkane** [comment] 2017-03-14 21:47
@taisdesouzalessa - hmm, I think this one is on the edge. I guess we can leave it as p1 for now. Thanks!
