### ISSUE TITLE
CMS-ify the left column "Latest from the Network"

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network#567] opened 2017-07-14 23:20 UTC
The item in the left column of the "Latest from the Network" section of the homepage is currently hardcoded.

Can we CMS-ify it?

**Comment by alanmoo** [comment] 2017-07-17 17:08
Dupe of #328, but it has a better title. Closing this and renaming that.

**Closed by alanmoo** 2017-07-17 17:08 UTC
