### ISSUE TITLE
Mozilla logo is a black box in Firefox

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network#591] opened 2017-07-20 14:22 UTC
<img width="369" alt="screen shot 2017-07-20 at 10 20 37 am" src="https://user-images.githubusercontent.com/1682681/28422148-2f6f73f8-6d35-11e7-9de8-cb1c465461ea.png">

**Comment by xmatthewx** [comment] 2017-07-20 14:29
Confirmed

**Comment by cadecairos** [comment] 2017-07-20 14:35
It's a statement about censorship!

**Comment by alanmoo** [comment] 2017-07-20 16:09
I think the issue is the fill style isn't being applied- perhaps we need to inline `fill: #fff` to [this line](https://github.com/mozilla/network/blob/master/source/images/mozilla-on-black.svg?short_path=1b84a67#L6)

**Comment by gvn** [comment] 2017-07-20 16:42
This appears to be a regression in FIrefox itself, because that SVG hasn't changed. You can see a black box on prod right now too without the new nav code landed.

**Comment by Pomax** [comment] 2017-07-20 17:04
This might also be a good time to switch over to the official Zilla Highlight font, which has the wordmark logo baked into it (the other Zilla font files don't) as a single glyph with fixed brand-approved dimensions, resolved as a standard ligature for the phrases `mozilla` and `Mozilla`.

**Closed** 2017-07-20 17:30 UTC
Labels: bug
