### ISSUE TITLE
Implement Featured Offering component (Home)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network#27] opened 2017-01-30 22:13 UTC
Simple structure for all offerings: Image, Short copy, link to page or URL, campaign ID.  

- [ ] styling

**Comment by xmatthewx** [comment] 2017-02-13 19:48
Tracking the offering content here: https://github.com/mozilla/network/issues/47

**Comment by gvn** [comment] 2017-03-02 22:04
From what I gather this is being redesigned. Please let me know if that's incorrect @xmatthewx. Marking blocked for now.

**Comment by gvn** [comment] 2017-03-10 19:43
Still waiting for design. @taisdesouzalessa can you update here when you have finished?

**Comment by gvn** [comment] 2017-03-10 19:44
Related #104

**Comment by gvn** [comment] 2017-03-13 19:04
Closing as dupe of #141

**Closed by gvn** 2017-03-13 19:04 UTC
Labels: engineering, in progress, p1
